# Настройки руны бессмертия
rune-settings:
  # Название предмета
  display-name: "&6«Бессмертие»"
  # Материал предмета
  material: ORANGE_DYE
  # Длительность неуязвимости в тиках (20 тиков = 1 секунда)
  invulnerability-duration: 60
  # Стоимость починки в наковальне
  anvil-repair-cost: 10

# Сообщения
messages:
  no-permission: "&cУ вас нет прав на использование этой команды!"
  player-not-found: "&cИгрок не найден!"
  invalid-amount: "&cНекорректное количество!"
  give-success: "&aВы успешно выдали &e{amount} &aрун бессмертия игроку &e{player}&a!"
  usage: "&eИспользование: /litetotemrune give <игрок> <количество>"

# Лор руны
rune-lore:
  - "&8Эффект руны"
  - " "
  - "&5 &7Особенности:"
  - "&5 &6 - после активации тотема с этим эффектом,"
  - "&5 &0.&6   Вы получите неуязвимость к урону"
  - "&5 &0.&6   продолжительностью 3 секунды;"
  - "&5 &6 - возможность наложить данный эффект"
  - "&5 &0.&6   на тотем через наковальню;"
  - " "

# Лор тотема с эффектом
totem-lore:
  - ""
  - "&5&o&x&4&0&8&B&F&BЭффекты при активации: "
  - "&5&o &6• Бессмертие"
  - " "
  - "&5&o&7Применяется после использования"